---
title: "hw_wk4"
output: html_document
---

```{r setup, include=FALSE}
options(repos = c(CRAN = "https://cran.rstudio.com"))
```

## Corrected version of hw4 in R markdown format: 


```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
install.packages('countrycode')
library(countrycode)
```

### Reading in Data 

```{r}
here::here()

WorldRaw <- st_read(here::here("hw_wk4_data",
                                   "World_Countries_(Generalized).geojson"))

UNDPRaw <- read_csv(here::here("hw_wk4_data",
                               "HDR23-24_Composite_indices_complete_time_series.csv"),
                    locale = locale(encoding = "latin1"),
                       na = " ", skip=0)
```

### Cleaning Data 

#### I'm choosing to join the data using country names (rather than country codes)
  
```{r}
UNDPcols<- UNDPRaw %>%
  clean_names()%>%
  select(country, gii_2019, gii_2010)%>%
  mutate(difference=gii_2019-gii_2010)

WorldClean <- WorldRaw %>% 
  clean_names()
```

### Join 

```{r}
Join_UNDP_World <- WorldClean %>% 
  left_join(., 
            UNDPcols,
            by = "country")
```

###Creating an Interactive Map 

```{r}
install.packages("leafpop")
library(leafpop)
install.packages("leaflet")
library(leaflet)
library(tmap)
library(tmaptools)
```
#Removing the geometry for our pop up boxes:

```{r}

popupUNDP <-Join_UNDP_World %>%
  st_drop_geometry()%>%
  dplyr::select(`difference`, country)%>%
  popupTable()

tmap_mode("view")

```
setting the color for breaks: 

```{r}
breaks=c(-0.009,-0.007, -0.005,-0.002,-0.015, -0.1)
pal1 <- Join_UNDP_World %>%
  colorBin(palette = "YlOrRd", domain=.$`difference`, bins=breaks)

map<- leaflet(Join_UNDP_World) %>%
  addPolygons(color="white", 
              weight = 2,
              opacity = 1,
              dashArray = "3",
              popup = popupUNDP,
              fillOpacity = 0.7,
              fillColor = ~pal1(`difference`),
              group = "difference")%>%
  
  #add basemaps
  addTiles(group = "UNDP (default)") %>%
  addProviderTiles(providers$Stadia.StamenToner, group = "Toner") %>%
  addProviderTiles(providers$Stadia.StamenTonerLite, group = "Toner Lite") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB")%>%
  
  # add a legend
  addLegend(pal = pal1, values = ~`difference`, group = c("difference"), 
            position ="bottomleft", title = "UNDP gii Differnce") %>%
  # specify layers control
  addLayersControl(
    baseGroups = c("UNDP (default)", "Toner", "Toner Lite", "CartoDB"),
    options = layersControlOptions(collapsed = FALSE)
  )

map
```





